### ISSUE TITLE
Dashboard Styling

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/WebCraftifyAI#10]
The user interface of the dashboard needs more attention and better styling.

Anybody can contribute or come up with fresh ideas.

**Comment by NtemKenyor** [comment]
We are still open to receive more design options about how the dashboard should look like. However, I will just keep this issue open for the main time.

**Comment by akashyadav24** [comment]
can you please assign it to me?

**Comment by NtemKenyor** [comment]
Sure.

**Comment by NtemKenyor** [comment]
@akashyadav24 hope you are doing great?
I Just wanted to checkup on you. How is everything going?

**Comment by akashyadav24** [comment]
Sorry for the delay...I am working on it 
ill submit it till Thursday

**Comment by NtemKenyor** [comment]
alright. No problem.

**Comment by SriChandana98** [comment]
Hi @NtemKenyor ,

Is the issue still open?
